# Generated by Django 3.2 on 2021-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('details', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
