# Generated by Django 3.2 on 2021-06-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='google_news',
            old_name='field_name',
            new_name='image_url',
        ),
    ]
