# Generated by Django 3.2 on 2021-06-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_field_name_google_news_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google_news',
            name='email',
        ),
    ]
